title: EJ's blog
author: ejayyy
email: ejay0811@gmail.com
show_excerpts: false
excerpt_separator: <!--more-->

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /:categories/:title/:short_month/:day
texture:
  title: EJ
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  social_links:
    github:  ejayyy

plugins:
  - jekyll-seo-tag